### ISSUE TITLE
Can we get an updated release with the 3000+ changes that have been made to the source repo in the last year?

### ISSUE THREAD

**Issue by dcorbin** [andymeneely/game_icons#10]
P.S.   Tried to figure out how to build local gem with new content, and couldn't.   `rake update` pulls the latests content, but the seems to write to an alternate location that the gem isn't actually using.

**Comment by andymeneely** [comment]
Done! And `rake update` is cleaned up to be less flaky and it's documented on the README in case you need to update again.
