### ISSUE TITLE
Pad the colors to recolor with a #

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/game_icons#5]
After seeing this: https://stackoverflow.com/questions/46508404/gameicons-get-recolor-always-results-in-a-solid-black-square/46526175#46526175

We should be consistent with Squib and put that `#` in front of every color string if it's not there.

**Comment by andymeneely** [comment]
We'll also need to make sure this is unit tested.

**Comment by TheRealDarkCoder** [comment]
Pull request added with #5 fixed in 1 file
